export const dbPortarias = [
  {
    id: '001',
    motorista: 'Matheus Castro Rocha',
    destino: 'Mossoró/RN',
    dataViagem: '20/09/2023',
    duracao: '0.5',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '002',
    motorista: 'Martim Alves Barbosa',
    destino: 'Natal/RN',
    dataViagem: '21/09/2023',
    duracao: '1',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '003',
    motorista: 'Daniel Rodrigues Barbosa',
    destino: 'Alexandria/RN',
    dataViagem: '22/09/2023',
    duracao: '0.5',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '004',
    motorista: 'Matheus Castro Rocha',
    destino: 'Mossoró/RN',
    dataViagem: '23/09/2023',
    duracao: '0.5',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '005',
    motorista: 'Martim Alves Barbosa',
    destino: 'Mossoró/RN',
    dataViagem: '23/09/2023',
    duracao: '0.5',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '006',
    motorista: 'Paulo Gomes Araujo',
    destino: 'Natal/RN',
    dataViagem: '23/09/2023',
    duracao: '1',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '007',
    motorista: 'Daniel Rodrigues Barbosa',
    destino: 'Mossoró/RN',
    dataViagem: '24/09/2023',
    duracao: '0.5',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '008',
    motorista: 'Matheus Castro Rocha',
    destino: 'Mossoró/RN',
    dataViagem: '24/09/2023',
    duracao: '0.5',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '009',
    motorista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '010',
    motorista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '011',
    motorista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '012',
    motorista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '013',
    motorista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '014',
    motorista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '015',
    motorista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
  {
    id: '016',
    motorista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkMem: 'www.google.com.br',
    linkPor: 'www.google.com.br',
  },
]
