export const portarias = [
  {
    id: '001',
    morotista: 'Matheus Castro Rocha',
    destino: 'Mossoró/RN',
    dataViagem: '20/09/2023',
    duracao: '0.5',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '002',
    morotista: 'Martim Alves Barbosa',
    destino: 'Natal/RN',
    dataViagem: '21/09/2023',
    duracao: '1',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '003',
    morotista: 'Daniel Rodrigues Barbosa',
    destino: 'Alexandria/RN',
    dataViagem: '22/09/2023',
    duracao: '0.5',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '004',
    morotista: 'Matheus Castro Rocha',
    destino: 'Mossoró/RN',
    dataViagem: '23/09/2023',
    duracao: '0.5',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '005',
    morotista: 'Martim Alves Barbosa',
    destino: 'Mossoró/RN',
    dataViagem: '23/09/2023',
    duracao: '0.5',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '006',
    morotista: 'Paulo Gomes Araujo',
    destino: 'Natal/RN',
    dataViagem: '23/09/2023',
    duracao: '1',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '007',
    morotista: 'Daniel Rodrigues Barbosa',
    destino: 'Mossoró/RN',
    dataViagem: '24/09/2023',
    duracao: '0.5',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '008',
    morotista: 'Matheus Castro Rocha',
    destino: 'Mossoró/RN',
    dataViagem: '24/09/2023',
    duracao: '0.5',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '009',
    morotista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '010',
    morotista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '011',
    morotista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '012',
    morotista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '013',
    morotista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '014',
    morotista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '015',
    morotista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
  {
    id: '016',
    morotista: 'Antônio Araujo Rocha',
    destino: 'Natal/RN',
    dataViagem: '24/09/2023',
    duracao: '1',
    linkPor: 'www.google.com.br',
    linkMem: 'www.google.com.br',
  },
]
